@startuml
left to right direction
Cliente -- (Mostrar menú)
@enduml
@startuml
left to right direction
rectangle {
(Mostrar menú)
(Pedir comida)
}
Cliente -- (Mostrar menú)
Cliente -- (Pedir comida)
(Mostrar menú) -- Restaurante
(Entregar comida) -- Restaurante
@enduml
@startuml
left to right direction
Cliente -- (Confirmar pedido)
Cliente -- (Cancelar pedido)
(Cancelar pedido) ..> (Devolver cambio) : <<include>>
(Confirmar pedido) ..> (Devolver cambio) : <<include>>
@enduml
@startuml
left to right direction
Cliente -- (Reservar vuelo)
:Cliente VIP: -- (Elegir asientos)
Cliente <|- :Cliente VIP:
@enduml
@startuml
left to right direction
Cliente -- (Meter dinero)
Cliente -- (Pedir azucar)
Cliente -- (Pedir producto)
Cliente -- (Cancelar)
(Pedir producto) ..> (Devolver dinero) : <<include>>
(Cancelar) ..> (Devolver dinero) : <<include>>
@enduml
@startuml
left to right direction
Cliente -- (Identificarse)
Cliente -- (Pagar)
Cliente -- (Elegir mensajero)
Cliente -- (Confirmar)
(Identificarse) <.. (Registrarse)
(Pagar) <|-- (Pagar con tarjeta)
(Pagar) <|-- (Pagar con transferencia)
@enduml
@startuml
left to right direction

Usuario -- (Iniciar sesión)
Usuario -- (Recuperar contraseña)
Usuario -- (Modificar contraseña)
Usuario -- (Cerrar sesión)
Administrador -- (Registrar usuario)
Administrador -- (Instalar programa)
Usuario <|- Administrador
@enduml
@startuml
left to right direction
Ciudadano --(Registrar entrada)
Ciudadano <|- :Ciudadano extranjero:
:Ciudadano extranjero: -- (Tomar huellas)
(Registrar entrada) <. (Tomar huellas) : <<extend>>
@enduml
@startuml
left to right direction
usecase UC1 as "Sacar dinero
----
+ solicitud hecha

"
usecase UC2 as "Retener tarjeta


    "
UC1 <.. UC2 : <<extend>>
note "Description\n\n condición:\n  { historia sospechosa }\npunto de extensión:\n  solicitud hecha" as n1
n1 -- UC2

@enduml